### ISSUE TITLE
关于应用内提示更新

### ISSUE THREAD

**Issue by shanren200** [SGPublic/BiliBangumiDownloader#1]
大佬，有个问题，一打开应用提示更新，按取消直接退出了，按确定下载的就不是apk，连文件管理器里面都看不到，只能在下载管理器里面看见，点击也没反应，下载最新release也提示更新。

**Comment by SGPublic** [comment]
> 大佬，有个问题，一打开应用提示更新，按取消直接退出了，按确定下载的就不是apk，连文件管理器里面都看不到，只能在下载管理器里面看见，点击也没反应，下载最新release也提示更新。

release上还没上传最新版本，你那边下载下来是什么格式？机型？

**Comment by shanren200** [comment]
无后缀的文件，lg g7

**Comment by shanren200** [comment]
> > 大佬，有个问题，一打开应用提示更新，按取消直接退出了，按确定下载的就不是apk，连文件管理器里面都看不到，只能在下载管理器里面看见，点击也没反应，下载最新release也提示更新。
> 
> release上还没上传最新版本，你那边下载下来是什么格式？机型？

无后缀的文件，官方文件管理器识别是安装包，第三方文件管理器直接看不见。LG G7

**Comment by SGPublic** [comment]
3.2.2.200919版本已尝试修复，从release中获取即可。

**Comment by shanren200** [comment]
谢谢大佬了
