### ISSUE TITLE
可以添加APP内下载进度的界面吗

### ISSUE THREAD

**Issue by Tianzhen1016** [SGPublic/BiliBangumiDownloader#2]
状态栏只有取消功能...有点难定

如果可以的话，麻烦大佬了

**Comment by SGPublic** [comment]
这个是调用的系统下载器，直接打开系统自带下载器进行管理就好~

**Comment by Tianzhen1016** [comment]
虽然没找到华为手机的下载管理器...但是出现了下一段通知栏突然消失一会 然后又出现的现象

**Comment by SGPublic** [comment]
只要是Android都会有系统自带下载器的，你的这个情况大概是EMUI的问题

**Comment by Tianzhen1016** [comment]
啊这...耽误大佬时间了...谢谢大佬让我涨姿势了
